title: Stackbit App Theme
baseURL: https://caksup.github.io/elite-planets/
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
